### ISSUE TITLE
Add example to docs for wallet importing

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fdp-storage#105]
Add example to docs for wallet importing with 

```
setAccountFromMnemonic
```

**Comment by crtahlin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fair-Data-Protocol-61f37a061754030017d022ea/issues/fairDataSociety/fdp-storage/105?planning-poker) with ZenHub @IgorShadurin @nugaon
