### ISSUE TITLE
Integration test for FairOS

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fdp-storage#108]
The main operations:
- pod listing
- directory listing
- authentification

Have to be covered by tests.

**Comment by tfius** [comment]
write a js app that tests FairOS-FDP functionality
1. create account
2. create pod
3. create folder
4. upload file
5. import account into FairOS 
6. check to see if pod, folder and file exists, 
7. check contents of file (same)
9. repeat process using FairOS (create account, pod, folder, file)
10. check from fdp-storage

Good starting point would be [create ](https://github.com/fairDataSociety/fdp-create-account)

**Comment by crtahlin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fair-Data-Protocol-61f37a061754030017d022ea/issues/fairDataSociety/fdp-storage/108?planning-poker) with ZenHub @IgorShadurin @nugaon

**Comment by IgorShadurin** [comment]
Add test for public key
