### ISSUE TITLE
Super Beeson

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fdp-storage#109]

**Comment by crtahlin** [comment]
From meeting: Ready, tests are running.

**Comment by crtahlin** [comment]
https://github.com/fairDataSociety/beeson/tree/feat/lets-roll

**Comment by crtahlin** [comment]
https://github.com/fairDataSociety/beeson/tree/feat/lets-roll

**Comment by tfius** [comment]
done and merged to master 28c2b7c843bd7375d08a43f6b3b7afbbdbed0ae1
