### ISSUE TITLE
Replace evm_mine with waitForTransaction

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fdp-storage#115]
Replace `evm_mine` with `waitForTransaction` in tests.
It is necessary for supporting not only Ganache but other networks.

**Comment by crtahlin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fair-Data-Protocol-61f37a061754030017d022ea/issues/fairDataSociety/fdp-storage/115?planning-poker) with ZenHub @IgorShadurin @nugaon

**Comment by IgorShadurin** [comment]
Resolved in https://github.com/fairDataSociety/fdp-storage/pull/132
