### ISSUE TITLE
Prepare tests for account creation and retrieval

### ISSUE THREAD

**Issue by tfius** [fairDataSociety/fdp-storage#17]

**Comment by tfius** [comment]
Tests should be done in accordance with https://docs.google.com/document/d/1OVMJnha6WQ8gmuPDqpOMQdzPGK1b_dsSEJUBikyL_xk/edit 

and should come to same functionality as current FairOS reference implementation

**Comment by IgorShadurin** [comment]
> Tests should be done in accordance with https://docs.google.com/document/d/1OVMJnha6WQ8gmuPDqpOMQdzPGK1b_dsSEJUBikyL_xk/edit
> 
> and should come to same functionality as current FairOS reference implementation

I don't have access to the file. Requested access

**Comment by nugaon** [comment]
Closed by https://github.com/fairDataSociety/fdp-storage/pull/30
