### ISSUE TITLE
Bump to BeeJS v6.0.0-pre

### ISSUE THREAD

**Issue by nugaon** [fairDataSociety/fdp-storage#171]
BeeJS released its new ESM build with [a beta tag](https://www.npmjs.com/package/@ethersphere/bee-js/v/6.0.0-pre.0) that the library should update to, replacing the FDS hotfix of `bee-js`

**Comment by IgorShadurin** [comment]
This version has problems working with jest, a testing framework. Jest can't use it so the new version is the ECMAScript module. Most likely there is a set of configurations that will allow this module to work, but I did not find a working one.
No comments from the developers yet.
