### ISSUE TITLE
passing POD properties to directory/file fetching

### ISSUE THREAD

**Issue by nugaon** [fairDataSociety/fdp-storage#176]
On every directory/file metadata fetch, a lookup happens for the latest POD list in the Personal storage.

Because most of the cases the applications work within specific PODs only, the before mentioned lookup is an overhead on the directory/file operations.

There should be an exported interface for directory/file operations that allows passing existing POD properties to perform the action.

**Comment by IgorShadurin** [comment]
I don't think adding specific POD properties is a good idea for the current use cases. The information can be calculated internally, so it's not necessary to pass it externally.

It might make sense to add these properties if there are specific use cases that require them, but for now I think it's better to keep as described by me above.

**Comment by nugaon** [comment]
If we choose caching, then let's do subtle changes. Start with the POD caching, since it reduces `getWalletByIndex` calls as well.

I think the caching of pod wallets should happen by their name that store `ExtendedPodInfo` in memory. 
Thereby, the `getExtendedPodList` won't be called if there is a stored record for `podName`.

> As an additional feature, the function could be implemented to automatically update the cache every 1 minute with the latest data.

Do not do that, the operations should happen by actions only.
The cache must be updated on every POD delete and the fetches can happen only when there is no corresponding record in the cache.


> Additionally, the function could support a new option to force the `getWalletByIndex` function to be called, which would allow the function to generate wallet data instead of using the cached value.

I do not really see now why do you need that. from a seed providing an index you can just init the wallet in one way.

I would wait with any other caching, because I think the next task must be to change epoch-based feeds to sequential one.

**Comment by molekilla** [comment]
Swarm Feeds Sequential is faster, use this please

**Comment by IgorShadurin** [comment]
Caching should work with workers. Cache should be restorable.
