### ISSUE TITLE
Basic Functionality

### ISSUE THREAD

**Issue by tfius** [fairDataSociety/fdp-storage#2]
simple functionality of FDP extension:

FDP has to get **sessionId** (directly request) that Swarm extension can reference
Research external signer
FDP logins to account without sharing my credentials with anyone
can upload my data to swarm encrypted by passphrase
can login from another location to retrieve my data 

@crtahlin @nugaon need to finalize this

draft it in here: https://hackmd.io/@crtahlin/BygD8SSRY

**Comment by tfius** [comment]
referencing this, to see limitations and feature summary
https://developer.chrome.com/docs/extensions/mv3/intro/mv3-overview/

**Comment by crtahlin** [comment]
This seems like it is probably obsolete, as it had to be done already? Closing it.

If not, please reopen, but modify title and update status and what needs to be done. @tfius
