### ISSUE TITLE
use case for "reuploadPortableAccount" unclear 

### ISSUE THREAD

**Issue by rampall** [fairDataSociety/fdp-storage#200]
```
// If necessary, the account can be re-uploaded to Swarm.
await fdp.personalStorage.reuploadPortableAccount('username', 'password')
```

From the readme it is unclear why this "reuploadPortableAccount" would be necessary. 
Is it temporary for migration? 
Is it mandatory to call this after registration? 
When or how often should one reupload a portable account? And why is it needed?

**Comment by crtahlin** [comment]
@IgorShadurin can probably give the info.

**Comment by IgorShadurin** [comment]
> ```
> // If necessary, the account can be re-uploaded to Swarm.
> await fdp.personalStorage.reuploadPortableAccount('username', 'password')
> ```
> 
> From the readme it is unclear why this "reuploadPortableAccount" would be necessary. Is it temporary for migration? Is it mandatory to call this after registration? When or how often should one reupload a portable account? And why is it needed?

This feature is not required for registration or migration. It is needed for some cases when data may disappear from the storage (for example, the stamp has expired)
