### ISSUE TITLE
Failed to construct 'Request': The `duplex` member must be specified for a request with a streaming body

### ISSUE THREAD

**Issue by rampall** [fairDataSociety/fdp-storage#221]
error thrown while creating pod `personalStorage.create`

![image](https://user-images.githubusercontent.com/520570/222937137-7f477fda-d925-4420-9454-02a6c4873208.png)

**Comment by IgorShadurin** [comment]
Fixed after updating bee-js dependency.

How to check:

- Clone the repo, install deps with `npm ci`

- Compile for browser
`npm run compile:browser`

- Run http-server inside the root
`npx http-server`

- Open `http://127.0.0.1:8080/test/manual/`

- Set actual postage stamp, create FDP, create Account, enter pod name, create pod
