### ISSUE TITLE
Uploading and downloading files in chunks

### ISSUE THREAD

**Issue by tomicvladan** [fairDataSociety/fdp-storage#258]
In the Blossom extension, files are transferred between processes. There is a limitation on maximum data size that can be transferred. Probably it depends of operating system, but it's around 50MB. That means all files larger than that won't be possible to transfer and use in Blossom.

To overcome this limitation, the fdp-storage library should provide an API for file uploading and downloading in chunks. In such a way that an async function will be called for every chunk. It's important that the functions be completely stateless, so all the information about uploaded/downloaded chunks must be passed to functions as argument. This is important because in browser extensions, the service worker script can be terminated at any time. It would be ideal if the user can define number of chunks or chunk size.

**Comment by IgorShadurin** [comment]
Implemented in https://github.com/fairDataSociety/fdp-storage/pull/270 and https://github.com/fairDataSociety/fdp-storage/pull/271
