### ISSUE TITLE
Increase pods/files limit

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fdp-storage#290]
Enhance the capacity for storing pods and files by developing a system that allows the linking of multiple chunks. This enhancement should include the following safeguards:

- The user interface, similar to that of Fairdrive, should not permit manual creation of direct links to chunks.
- The system must prevent the formation of circular references, where chunks inadvertently link back to themselves either directly or through a series of connections.
---
A method to expand the storage capacity for pods and files involves changing how we save their data. Instead of keeping the information directly in the SOC, which has a size limit, we store the data as bytes (encrypted on the user side + swarm side). We then keep a reference to these bytes in the SOC. This approach allows us to bypass the size limitations of SOC, enabling us to store a vastly greater number of items, potentially in the millions. However, if necessary, we can still set a cap on the number of items.

To ensure a seamless transition for users, both FairOS-dfs and FDP Storage are designed to support the migration from the old system to this new method without interrupting the user experience. Users won't even notice the change as it happens in the background.

We should also gzip the data by default, to reduce size.

**Comment by asabya** [comment]
We should also gzip the data by default, to reduce size.

**Comment by crtahlin** [comment]
Related to https://github.com/fairDataSociety/fairOS-dfs/issues/554
