### ISSUE TITLE
Tests JS-FairOS

### ISSUE THREAD

**Issue by tfius** [fairDataSociety/fdp-storage#37]

**Comment by crtahlin** [comment]
What is the purpose of this ticket? Please make the title more informative and and add a description on the purpose of this ticket, specifically, when will it be closed (what is the acceptance criteria).

**Comment by crtahlin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fair-Data-Protocol-61f37a061754030017d022ea/issues/fairDataSociety/fdp-storage/37?planning-poker) with ZenHub @IgorShadurin @nugaon
