### ISSUE TITLE
Store shared references under special pod for that

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fdp-storage#62]

**Comment by tfius** [comment]
.references ?

**Comment by asabya** [comment]
1) we store the pod sharedInfo (pinned) -> share the reference to the sharedInfo -> Now in any case if we don't want to share it with any new user we simply delete (unpin) the reference to sharedInfo -> now after cleanup even if anyone has the reference to sharedInfo, the sharedInfo is not available anymore.

2) We add temp share feature, i.e. store share info unpinned -> Other user receives it -> it should be gone after garbage collection

- We store the references of sharedInfo that are pinned in a seperate pod (.references). we remove the reference and unpin it when the owner wants to revoke access to new users for any specific sharedInfo

**Comment by crtahlin** [comment]
What is the purpose of storing the shared references in special pod, please elaborate @IgorShadurin

**Comment by IgorShadurin** [comment]
No purpose for that
