### ISSUE TITLE
Issue when overriding the default settings

### ISSUE THREAD

**Issue by tomicvladan** [fairDataSociety/fdp-storage#83]
When an instance of the `FdpStorage` class is created, there are just two options. Whether to omit the third options parameter or to specify it completely with all its properties.

It would be much more useful if it could be possible to provide partial configuration with just fields that need to different. All other fields could implicitly use the default values.

**Comment by crtahlin** [comment]
Please decide on the suggestion and specify desired behavior and/or put in appropriate state on kanban board @nugaon .

**Comment by crtahlin** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fair-Data-Protocol-61f37a061754030017d022ea/issues/fairDataSociety/fdp-storage/83?planning-poker) with ZenHub @nugaon

**Comment by nugaon** [comment]
@tomicvladan, could you please write an example for your proposal?

IMO to handle the optional parameters in a [options object](https://github.com/fairDataSociety/fdp-storage/blob/master/src/types.ts#L7-L20) with all fields optional is not a bad practice. These have default values even though it is not indicated on its interface.

**Comment by crtahlin** [comment]
@tomicvladan please check if this is still relevant

**Comment by IgorShadurin** [comment]
Options can defined partially. Example https://github.com/fairDataSociety/fdp-storage/blob/1c4a4871074f80ef6bf496640e66f0ee75f51257/test/integration/fdp-class.spec.ts#L32
