### ISSUE TITLE
Can't connect the FDP library to my project in React Native

### ISSUE THREAD

**Issue by igar1991** [fairDataSociety/fdp-storage#87]
Hello. I participate in the bounty https://gitcoin.co/issue/29075
Unfortunately, I can't connect the FDP library to my project in React Native. There is a suspicion of the src/shim/crypto.ts file.
![image](https://user-images.githubusercontent.com/43186611/178715997-fb876cd7-8dc9-4ac5-86a9-e0b4fd6d1840.png)

**Comment by IgorShadurin** [comment]
#67

**Comment by crtahlin** [comment]
@igar1991 Does this solve the issue for you?

**Comment by igar1991** [comment]
Hello.  I can the connect FDP library to my project in React Native. But I have problem with Uploading binary data:
https://github.com/fairDataSociety/fdp-storage/issues/110
https://github.com/ethersphere/bee-js/issues/757

What should I do?
