### ISSUE TITLE
Pod creation with hdwallet.fromSeed

### ISSUE THREAD

**Issue by asabya** [fairDataSociety/fdp-storage#90]
As of now fairOS-dfs used mnemonic to generate the pod accounts, but with portable login and using [private key](https://github.com/fairDataSociety/fdp-storage/blob/34ed9dc01d870cc8283b2a0793c69e67ba00e57b/src/utils/wallet.ts#L10) to generate the pod account results in creating different pod account.

This will be a huge problem for existing fairOS users. Even if we have migration for user account, we will not be able to access existing pods.

**Comment by tfius** [comment]
Oh this is a problem,
how could we do migration of the old pods ?
we could store required data in a similar way in a different SOC with some
other mnemonic.

**Comment by asabya** [comment]
We can try... but generating wallet from private key instead of a seed seems to be a hack.

**Comment by asabya** [comment]
We opted for storing seed in the soc for authentication and generate pod accounts from that
