### ISSUE TITLE
This statements repeats on a lot of places. It could be extracted to a private method

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fdp-storage#98]
This statements repeats on a lot of places. It could be extracted to a private method?

_Originally posted by @tomicvladan in https://github.com/fairDataSociety/fdp-storage/pull/97#discussion_r932164244_

**Comment by crtahlin** [comment]
Does it make sense to do as suggested @nugaon ?

**Comment by IgorShadurin** [comment]
implemented
